apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-tuning
data:
  nginx.conf: |
    worker_processes auto;
    events {
      worker_connections 65535;
      multi_accept on;
      use epoll;
    }
    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 30;
      keepalive_requests 10000;
      server_tokens off;
      client_max_body_size 10m;

      server {
        listen 8080;
        root /usr/share/nginx/html;
        index index.html;
        location /healthz { return 200 "ok\n"; }
      }
    }
